### ISSUE TITLE
프로젝트, 메신저, 캘린더 마무리 작업

### ISSUE THREAD

**Issue by random-blossom** [Witty-Puppy/Backend#36]
1. 자잘한 오류 수정
2. 안 쓰게 된 코드 정리
3. Swagger 설정 추가
4. 코드 짜는 동안 사용했던 logging 제거

**Comment by JunKyeong-Lee** [comment]
쿼리문 관련. 프로젝트 게시판 내역 들고 올때 이미 마감된걸 제일 후순위에.

대신 얼마 안남은건 우선순위를 높여서 쿼리문을 신청해야 한다.

**Comment by JunKyeong-Lee** [comment]
프론트에서 백에 전달할떄 lockedStatus. progressStatus 중 프로젝트 생성이 전달되지 않는다.
